FROM openjdk
WORKDIR usr/src
ADD ./target/FavouriteMovieService-0.0.1-SNAPSHOT.jar /usr/src/FavouriteMovieService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","FavouriteMovieService-0.0.1-SNAPSHOT.jar"]
